(library
 (name lib)
 (libraries gmp ppl extlib fileutils str unix threads)
 (modules_without_implementation
  abstractModel
  abstractProperty
  automaton
  parsingStructure
  result))

(ocamllex
 (modules ModelLexer PropertyLexer ModelUpdateLexer))

(menhir
 (flags --dump --explain)
 (modules ModelParser PropertyParser ModelUpdateParser))

(rule
 (targets ModelParser.conflicts)
 (deps ModelParser.mly)
 (action
  (run menhir --dump --explain %{deps})))

(rule
 (targets PropertyParser.conflicts)
 (deps PropertyParser.mly)
 (action
  (run menhir --dump --explain %{deps})))

(rule
 (targets ModelUpdateParser.conflicts)
 (deps ModelUpdateParser.mly)
 (action
  (run menhir --dump --explain %{deps})))

(env
 (dev
  (flags
   (:standard -warn-error -A))))

(rule
 (targets BuildInfo.ml BuildInfo.mli)
 (deps
  (:gen ../../gen_build_info.py))
 (action
  (run python %{gen})))
