import os
import sys
import re
import itertools

def parse_input_file(filename):
    with open(filename, 'r') as f:
        content = f.read()
    
    transitions = {}
    lines = content.splitlines()
    current_loc = None

    for line in lines:
        line = line.strip()
        if line.startswith("loc "):
            current_loc = line.split()[1].replace(":", "")
            transitions[current_loc] = []
        elif "sync" in line and "goto" in line:
            action = re.search(r"sync\s+(\w+)", line).group(1)
            dest = re.search(r"goto\s+(\w+)", line).group(1)
            transitions[current_loc].append((action, dest))
    
    return transitions

def generate_sync_label(from_state, to_states):
    return from_state + ''.join(to_states)

def action_cost(action):
    # Extract number from aN
    return int(action[1:])

def powerset(iterable):
    s = list(iterable)
    return list(itertools.chain.from_iterable(itertools.combinations(s, r) for r in range(len(s) + 1)))

def generate_demon_automaton(transitions, max_cost=None):
    all_syncs = set()
    lines = []

    # Header
    lines.append("var\n\n(* Parameters *)\n\tp,maxp (* The cost of the demoniac strategy *)\n\t\t: discrete;\n\n")
    lines.append("(************************************************************)\n  automaton demon\n(************************************************************)\n")

    sync_labels = set()
    for src, edges in transitions.items():
        n = len(edges)
        if n == 0:
            continue

        combos = powerset(edges)
        combos = [c for c in combos if len(c) < n]  # can't cut all edges
        for combo in combos:
            dests = [e[1] for e in combo]
            label = generate_sync_label(src, dests) if dests else "pass"
            sync_labels.add(label)

    lines.append("synclabs: " + ",".join(sorted(sync_labels)) + ";\n")

    # To_sX locations
    all_locs = set(transitions.keys()) | {d for l in transitions.values() for _, d in l}
    for loc in sorted(all_locs):
        lines.append(f"loc To_{loc}: invariant p<=maxp\n\twhen True do {{}} goto {loc};\n")

    # Actual locations
    for src, edges in transitions.items():
        n = len(edges)
        if n == 0:
            lines.append(f"loc {src}: invariant True\n")
            continue

        lines.append(f"loc {src}: invariant True")
        combos = powerset(edges)
        combos = [c for c in combos if len(c) < n]  # no full cuts

        for combo in combos:
            if len(combo) == 0:
                # No cuts
                for (_, dest) in edges:
                    lines.append(f"\twhen True sync pass do {{}} goto To_{dest};")
            else:
                dests = [d for (_, d) in combo]
                label = generate_sync_label(src, dests)
                cost = sum(action_cost(a) for (a, _) in combo)
                for (_, d) in edges:
                    if d not in dests:
                        lines.append(f"\twhen True sync {label} do {{if p<{cost} then p := {cost} end}} goto To_{d};")
        
        lines.append("\n")

    lines.append("end (* demon *)\n\n")

    # Init and parameters
    maxp_val = max_cost if max_cost is not None else 0  # will be replaced if needed later
    lines.append("(************************************************************)\n(* Initial state *)\n(************************************************************)\n\n")
    lines.append("init :=\n\t& loc[demon] = s0\n\t& p = 0\n")
    lines.append(f"\t& maxp = {maxp_val}\n;\n\n")

    lines.append("(************************************************************)\n(* The end *)\n(************************************************************)\nend\n")
    return "\n".join(lines), maxp_val

def compute_max_cost(transitions):
    max_combo_cost = 0
    for edges in transitions.values():
        n = len(edges)
        combos = powerset(edges)
        combos = [c for c in combos if len(c) < n]
        for combo in combos:
            cost = sum(action_cost(a) for (a, _) in combo)
            max_combo_cost = max(max_combo_cost, cost)
    return max_combo_cost

def generate_imiprop_content(last_location):
    return f"""\
// Automatically generated by OL_translator.py

property := #synth <<demon(demon)>>AGnot(loc[demon] = {last_location}) ;
"""


def OL_translator(input_path, cost_limit):
    base_name = os.path.splitext(os.path.basename(input_path))[0]
    result_dir = "OL_translator_result"
    os.makedirs(result_dir, exist_ok=True)

    transitions = parse_input_file(input_path)
    max_cost = compute_max_cost(transitions) if cost_limit == 0 else cost_limit

    translated_content, _ = generate_demon_automaton(transitions, max_cost)
    header = f"// Automatically generated from {input_path} using OL_translator.py\n\n"
    translated_content = header + translated_content

    if cost_limit == 0:
        output_name = f"{base_name}_translated.imi"
    else:
        output_name = f"{base_name}_translated_maxp_{cost_limit}.imi"

    with open(os.path.join(result_dir, output_name), 'w') as f:
        f.write(translated_content)

    # last location: assume highest-indexed one in original transitions
    last_location = sorted(transitions.keys())[-1]
    imiprop_content = generate_imiprop_content(last_location)

    with open(os.path.join(result_dir, f"{base_name}_translated.imiprop"), 'w') as f:
        f.write(imiprop_content)

    print(f"Generated files in {result_dir}/")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python OL_translator.py input_file.imi cost_limit")
        sys.exit(1)
    
    input_file = sys.argv[1]
    try:
        cost_limit = int(sys.argv[2])
    except ValueError:
        print("Cost limit must be an integer")
        sys.exit(1)

    OL_translator(input_file, cost_limit)
