(tests
 (names imitatorUnitTests)
 (libraries alcotest fmt lib parsing entities utils)
 (flags
  (:standard -open Utils -open Entities))
 (action (run %{test} -e))
  (link_flags
  (:standard
   -cclib
   -lppl
   -cclib
   -lppl_ocaml
   -cclib
   -lstdc++
   -cclib
   -lgmp
   -cclib
   -lgmpxx))
 
 )

(env
  (dev
    (flags (:standard -warn-error -A))))
