#!/bin/sh
#
# Build the internal odoc API reference and bundle a branded HTML entry point.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$repo_root"

dune build @doc-private _build/default/_doc/_html/IMITATOR/index.html

html_dir="_build/default/_doc/_html"
index="$html_dir/index.html"
bundle_dir="doc/api/html"
theme_css="doc/api/assets/api-theme.css"
odoc_css="$html_dir/odoc.support/odoc.css"
logo_source="logos/imitator-500.png"
logo_target="odoc.support/imitator-500.png"

library_dir() {
  library_name=$1
  for path in "$html_dir"/"$library_name"@*; do
    if [ -d "$path" ]; then
      basename "$path"
      return
    fi
  done

  echo "$library_name"
}

utils_dir=$(library_dir utils)
data_structures_dir=$(library_dir data_structures)
parsing_dir=$(library_dir parsing)
entities_dir=$(library_dir entities)
lib_dir=$(library_dir lib)
algorithms_dir=$(library_dir algorithms)
exporter_dir=$(library_dir exporter)

if [ -f "$theme_css" ]; then
  tmp_css=$(mktemp "$odoc_css.XXXXXX")
  trap 'rm -f "$tmp_css"' EXIT
  {
    awk '/^\/\* IMITATOR API documentation theme\./ { exit } { print }' "$odoc_css"
    printf '\n\n'
    cat "$theme_css"
  } > "$tmp_css"
  mv "$tmp_css" "$odoc_css"
  chmod 0644 "$odoc_css"
  trap - EXIT
fi

tmp=$(mktemp "$index.XXXXXX")
trap 'rm -f "$tmp"' EXIT

cat > "$tmp" <<EOF
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>IMITATOR API reference</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" href="odoc.support/odoc.css"/>
  </head>
  <body class="api-home">
    <div class="api-shell">
      <header class="api-topbar">
        <div class="api-brand">
          <img class="api-logo" src="$logo_target" alt="IMITATOR logo"/>
          <span>IMITATOR API</span>
        </div>
      </header>

      <main>
        <section class="api-hero">
          <div class="api-hero-inner">
            <div>
              <p class="api-kicker">Internal developer reference</p>
              <h1>IMITATOR API Documentation</h1>
            </div>

            <aside class="api-panel" aria-label="Build information">
              <h2>Build locally</h2>
              <code class="api-command">opam install odoc
doc/scripts/build-api-reference.sh</code>
              <div class="api-meta">
                <div>
                  <span>Generated by</span>
                  <strong>odoc</strong>
                </div>
                <div>
                  <span>Scope</span>
                  <strong>@doc-private</strong>
                </div>
                <div>
                  <span>Bundle</span>
                  <strong>doc/api/html</strong>
                </div>
                <div>
                  <span>Package</span>
                  <strong>IMITATOR</strong>
                </div>
              </div>
            </aside>
          </div>
        </section>

        <section id="libraries" class="api-section">
          <div class="api-section-header">
            <h2>Libraries</h2>
            <p>
              The project is split into private libraries. Start with the package overview
              for the full odoc index, or jump directly to the subsystem you need.
            </p>
          </div>

          <div class="api-library-grid">
            <a class="api-library-card" href="$utils_dir/Utils/index.html">
              <span>Foundation</span>
              <h3>utils</h3>
              <p>General-purpose utilities, constants, diagnostics, counters, and support functions.</p>
            </a>
            <a class="api-library-card" href="$data_structures_dir/Data_structures/index.html">
              <span>Foundation</span>
              <h3>data_structures</h3>
              <p>Reusable data structures and caches shared by the model-checking layers.</p>
            </a>
            <a class="api-library-card" href="$entities_dir/Entities/index.html">
              <span>Domain</span>
              <h3>entities</h3>
              <p>Core abstract syntax, values, constraints, states, automata, and model types.</p>
            </a>
            <a class="api-library-card" href="$parsing_dir/Parsing/index.html">
              <span>Input</span>
              <h3>parsing</h3>
              <p>Model and property parsing infrastructure, metadata, and parsing utilities.</p>
            </a>
            <a class="api-library-card" href="$lib_dir/Lib/index.html">
              <span>Kernel</span>
              <h3>lib</h3>
              <p>Shared model-checking infrastructure, conversion, state-space machinery, and output processing.</p>
            </a>
            <a class="api-library-card" href="$algorithms_dir/Algorithms/index.html">
              <span>Analysis</span>
              <h3>algorithms</h3>
              <p>Synthesis and verification algorithms built on top of the shared symbolic infrastructure.</p>
            </a>
            <a class="api-library-card" href="$exporter_dir/Exporter/index.html">
              <span>Output</span>
              <h3>exporter</h3>
              <p>Output and export back-ends for generated artifacts and translated representations.</p>
            </a>
          </div>
        </section>
      </main>

      <footer class="api-footer">
        <p>Generated from IMITATOR source documentation. This reference is intended for contributors.</p>
      </footer>
    </div>
  </body>
</html>
EOF

mv "$tmp" "$index"
trap - EXIT

rm -rf "$bundle_dir"
mkdir -p "$bundle_dir"
cp -R "$html_dir/." "$bundle_dir/"
if [ -f "$logo_source" ]; then
  cp "$logo_source" "$bundle_dir/$logo_target"
fi
chmod -R u+w "$bundle_dir"

find "$bundle_dir" -name '*.html' -exec perl -0pi -e '
  s{<a href="[^"]+">Up</a>[^<]*}{}g;
  s{(>)([A-Za-z_][A-Za-z0-9_]*)@[0-9a-f]+(<)}{$1$2$3}g;
  s{(\()([A-Za-z_][A-Za-z0-9_]*)@[0-9a-f]+\.}{$1$2.}g;
  s{<a href="[^"]+">(utils|data_structures|parsing|entities|lib|algorithms|exporter)</a>\s*&#x00BB;\s*}{}g;
' {} +

echo "Bundled API reference in $bundle_dir"
